variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_doc
  - test
  - test_tag
  - publish



###################################################################################################
# Build documentation
###################################################################################################

build_documentation:
  stage: build_doc
  tags:
    - shell
  script:
    - source setup_env
    - cd doc/spect_fw_api
    - ts_latex_build.py spect_fw_doc.tex

  artifacts:
    name: spect_fw_documentation
    when: always
    paths:
      - doc/spect_fw_api/build/pdf/spect_fw_doc.pdf


###################################################################################################
# Run tests
###################################################################################################
run_test:
  stage: test
  tags:
    - shell
  script:
    - source ./setup_env
    - cd tests
    - ./run_tests.sh

run_test_tag:
  stage: test_tag
  tags:
    - shell
  only:
    - tags
  when: always
  script:
    - source ./setup_env
    - cd tests
    - ./run_tests.sh

###################################################################################################
# Publish doc to pages
###################################################################################################

pages:
    tags:
        - shell
    stage: publish
    when: always
    script:
        - echo "Publishing pages..."
        - mkdir -p public
        - cp doc/spect_fw_api/build/pdf/spect_fw_doc.pdf public

    artifacts:
        name: spect_fw_documentation
        paths:
            - public

###################################################################################################
# Mirror the public branch to Github
###################################################################################################
github_mirror:
    tags:
        - shell
    stage: publish
    when: always
    only:
      - public
    script:
      - source ./setup_env

      # Ensure we are on branch, not detached head
      - git checkout public

      # Configure GIT user to match the "gitlab-runner" that runs the pipeline
      # Match its email to "tropic-gitlab" users email that is used to connect to confluence
      - git config --global user.email "tropic-gitlab@tropicsquare.com"
      - git config --global user.name "gitlab-runner"

      # Add remote origin
      - git remote remove github || true
      - git remote add github git@github.com:tropicsquare/ts-spect-fw.git

      # Push - Use SSH key created for this purpose
      - GIT_SSH_COMMAND="ssh -i ~/.ssh/gitlab_mirror_ts_spect_fw.id_rsa" git push github
      - GIT_SSH_COMMAND="ssh -i ~/.ssh/gitlab_mirror_ts_spect_fw.id_rsa" git push github --tags
