- name : clear
  id : 0x00
  input :
  output :

############################################
# ECC Key Gen/Store
############################################
- name : ecc_key
  id : 0x60
  input :
    - name : cmd_in
      address : 0x00
  output :
    - name : result
      address : 0x00

- name : ecc_key_gen
  id : 0x60

- name : ecc_key_store
  id : 0x61
  input :
    - name : k
      address : 0x10

- name : ecc_key_read
  id : 0x62
  output :
    - name : pub_key
      address : 0x10

- name : ecc_key_erase
  id : 0x63

############################################
# Secure Channel
############################################
- name : x25519
  id : 0x10
  context :
    - name : etpriv
      address : 0x40
      base : 0x0000
    - name : ehpub
      address : 0x60
      base : 0x0000

- name : x25519_kpair_gen
  id : 0x11
  input:
  output:
    - name : etpub
      address : 0x20
      base : 0x1000

- name : x25519_sc_et_eh
  id : 0x12
  input:
    - name : ehpub
      address : 0x20
      base : 0x0000
  output:
    - name : r1
      address : 0x20
      base : 0x1000

- name : x25519_sc_et_sh
  id : 0x13
  input:
    - name : slot
      address : 0x20
      base : 0x0000
  output:
    - name : r2
      address : 0x20
      base : 0x1000

- name : x25519_sc_st_eh
  id : 0x14
  input:
  output:
    - name : r3
      address : 0x20
      base : 0x1000

############################################
# EdDSA
############################################
- name : eddsa
  id : 0x40
  input :
    - name : message
      address : 0x00
  output :
    - name : result
      address : 0x00

- name : eddsa_set_context
  id : 0x41
  input :
    - name : slot
      address : 0x00
    - name : sch
      address : 0xA0
      base : 0x0000
    - name : scn
      address : 0xC0
      base : 0x0000

- name : eddsa_nonce_init
  id : 0x42

- name : eddsa_nonce_update
  id : 0x43

- name : eddsa_nonce_finish
  id : 0x44

- name : eddsa_R_part
  id : 0x45

- name : eddsa_e_at_once
  id : 0x46

- name : eddsa_e_prep
  id : 0x47

- name : eddsa_e_update
  id : 0x48

- name : eddsa_e_finish
  id : 0x49

- name : eddsa_finish
  id : 0x4A
  output :
    - name : signature
      address : 0x10

- name : eddsa_verify
  id : 0x4B
  input :
    - name : R
      address : 0x20
      base : 0x0000
    - name : S
      address : 0x40
      base : 0x0000
    - name : pubkey
      address : 0x60
      base : 0x0000
    - name : message
      address : 0x80
      base : 0x0000
  output :
    - name : result
      address : 0x00
      base : 0x1000

############################################
# ECDSA
############################################
- name : ecdsa
  id : 0x70
  input :
    - name : cmd_in
      address : 0x00
    - name : message
      address : 0x10
  output :
    - name : result
      address : 0x00

- name : ecdsa_sign
  id : 0x70
  input :
    - name : sch
      address : 0xA0
      base : 0x0000
    - name : scn
      address : 0xC0
      base : 0x0000
  output :
    - name : signature
      address : 0x10

############################################
# SHA
############################################
- name : sha512
  id : 0x50
  input :
    - name : data0
      address : 0x10
      base : 0x0000
    - name : data1
      address : 0x30
      base : 0x0000
    - name : data2
      address : 0x50
      base : 0x0000
    - name : data3
      address : 0x70
      base : 0x0000

- name : sha512_init
  id : 0x51

- name : sha512_update
  id : 0x52
  
- name : sha512_final
  id : 0x53
  output :
    - name : digest0
      address : 0x10
      base : 0x1000
    - name : digest1
      address : 0x30
      base : 0x1000


############################################
# Debug
############################################

- name : x25519_dbg
  id : 0x9F
  input :
    - name : priv
      address : 0x20
      base : 0x0000
    - name : pub
      address : 0x40
      base : 0x0000
  output :
    - name : r
      address : 0x20
      base : 0x1000

- name : ecdsa_sign_dbg
  id : 0xAF
  input :
    - name : z
      address : 0x10
      base : 0x0000
    - name : d
      address : 0x40
      base : 0x0000
    - name : w
      address : 0x60
      base : 0x0000
  output :
    - name : r
      address : 0x10
      base : 0x1000
    - name : s
      address : 0x30
      base : 0x1000

- name : eddsa_set_context_dbg
  id : 0xBF
  input :
    - name : s
      address : 0x0040
    - name : prefix
      address : 0x0060
